"""
Question, MCQChoice, SourceReference, and AuditLog models for QuizSensei.
"""
import uuid
from datetime import datetime, timezone

from sqlalchemy import Column, String, Integer, Boolean, Float, DateTime, Text, ForeignKey
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship

from app.db.session import Base


class Question(Base):
    """
    A single quiz question generated by Agent 2 and audited by Agent 3.
    All user-facing text fields are in Thai.
    """
    __tablename__ = "v2_questions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    quiz_id = Column(UUID(as_uuid=True), ForeignKey("quizzes.id", ondelete="CASCADE"), nullable=False, index=True)

    question_order = Column(Integer, nullable=False, default=0)
    stem_th = Column(Text, nullable=False)  # Question text in Thai
    question_type = Column(String(20), nullable=False, default="mcq")
    difficulty = Column(String(20), nullable=False)
    blooms_level = Column(String(20), nullable=True)  # remember | understand | apply | analyze | evaluate | create

    # Answer
    correct_answer_key = Column(String(5), nullable=False)  # A | B | C | D
    rationale_correct_th = Column(Text, nullable=True)
    rationale_incorrect_th = Column(Text, nullable=True)
    design_reasoning_th = Column(Text, nullable=True)

    # Diagnostic distractor data
    distractor_map = Column(JSONB, nullable=True, default=dict)

    # Source grounding
    source_evidence_th = Column(Text, nullable=True)  # Citation from source text

    # Audit (Agent 3)
    audit_status = Column(String(20), nullable=False, default="pending")  # pending | approved | rejected
    audit_feedback_th = Column(Text, nullable=True)

    # Relationships
    quiz = relationship("Quiz", back_populates="questions")
    choices = relationship("MCQChoice", back_populates="question", cascade="all, delete-orphan", lazy="selectin")
    source_references = relationship("SourceReference", back_populates="question", cascade="all, delete-orphan", lazy="selectin")
    audit_logs = relationship("AuditLog", back_populates="question", cascade="all, delete-orphan")


class MCQChoice(Base):
    """A single answer choice for a multiple-choice question."""
    __tablename__ = "mcq_choices"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    question_id = Column(UUID(as_uuid=True), ForeignKey("v2_questions.id", ondelete="CASCADE"), nullable=False, index=True)

    choice_key = Column(String(5), nullable=False)  # A, B, C, D
    choice_text_th = Column(Text, nullable=False)
    is_correct = Column(Boolean, nullable=False, default=False)

    # Relationships
    question = relationship("Question", back_populates="choices")


class SourceReference(Base):
    """
    Maps a question back to its source text.
    Provides evidence for zero-hallucination grounding.
    """
    __tablename__ = "source_references"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    question_id = Column(UUID(as_uuid=True), ForeignKey("v2_questions.id", ondelete="CASCADE"), nullable=False, index=True)
    document_section_id = Column(UUID(as_uuid=True), ForeignKey("document_sections.id"), nullable=True)

    excerpt_th = Column(Text, nullable=True)  # Quoted text from source
    page_number = Column(Integer, nullable=True)
    document_filename = Column(String(500), nullable=True)
    confidence_score = Column(Float, nullable=True, default=1.0)  # 0-1

    # Relationships
    question = relationship("Question", back_populates="source_references")


class AuditLog(Base):
    """
    Tracks each audit attempt by Agent 3 on a question.
    Supports the regeneration loop where rejected questions are re-generated.
    """
    __tablename__ = "audit_logs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    question_id = Column(UUID(as_uuid=True), ForeignKey("v2_questions.id", ondelete="CASCADE"), nullable=False, index=True)

    attempt_number = Column(Integer, nullable=False, default=1)
    verdict = Column(String(20), nullable=False)  # approved | rejected
    feedback_th = Column(Text, nullable=True)
    audited_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    # Relationships
    question = relationship("Question", back_populates="audit_logs")
